### ISSUE TITLE
When A Breed is Updated/Deleted, the Breed List should be re rendered again

### ISSUE THREAD

**Issue by Andrsrz** [Andrsrz/tyra-web#8]
### Expected behaviour
Once a breed has been updated/deleted the breed list should be re rendered using custom events.

### Actual behaviour
You need to reload the page to have the updated/deleted breed list after updating one breed.

### I'm seeing this behaviour on

- [x] Firefox
- [x] Chrome/Chromium
- [x] Safari
- [x] Oepra

### I've checked these
- [x] It happens on a fresh NPM CLI project as well.
- [x] My JavaScript has no errors (`window.onerror` catches nothing).

**Comment by MilePaor** [comment]
Can i take this one @Andrsrz

**Comment by Andrsrz** [comment]
Of course! Go ahead @MilePaor. 

If you find yourself in trouble you can check the 'Service' components, it's basically the same functionality. And remember to update the corresponding tests.

**Comment by MilePaor** [comment]
I give up on this, please assign someone else.

**Comment by Andrsrz** [comment]
Ok, no worries.
